# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

. $HOME/.shells/defaults
. $HOME/.shells/functions
. $HOME/.shells/exports
. $HOME/.shells/alias

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

source $HOME/.shells/bash_prompt.sh
