# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
#
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

fpath+=${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions/src
# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    git
    vi-mode
    aws
    command-not-found
    docker
    git
    fzf
    npm
    nvm
    vscode
    web-search
    zsh-autosuggestions
    zsh-completions
)

source $ZSH/oh-my-zsh.sh
# User configuration

source $HOME/.shells/functions
source $HOME/.shells/exports
source $HOME/.shells/alias
export EDITOR='vim'
bindkey -M viins 'jj' vi-cmd-mode

eval "$(starship init zsh)"
